/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 space_age_radio.glb 
Author: Tom Seddon (https://sketchfab.com/bloodmeat08)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/space-age-radio-a3c888aed8424954b8e93980cd107fc6
Title: Space Age Radio
*/

"use client";

import React from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";

export function SpaceAgeRadio(props: any) {
  const { nodes, materials } = useGLTF(
    "/models/SpaceAgeRadio/space_age_radio.glb"
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={(nodes.Object_2 as THREE.Mesh).geometry}
        material={materials.None}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/models/SpaceAgeRadio/space_age_radio.glb");
